### ISSUE TITLE
Enable Travis CI for Repository

### ISSUE THREAD

**Issue by ChristianMurphy** [Jasig/SurveyPortlet#11]
Travis CI is configured, but it looks like the webhook has not been enabled.

To enable web hook:

1. login to https://travis-ci.org/
2. goto https://travis-ci.org/profile
3. view the `Jasig` organization
4. check `Jasig/SurveyPortlet`

Thanks!

cc @apetro  @bjagg  @drewwills

**Comment by apetro** [comment]
Done, I believe. May have to touch the git repo to get the hook to fire. I enabled the build-only-if-.travis-ci.yml-file-present, so will only apply to the right branches and this project can turn off the integration temporarily or permanently in the future simply by removing that text file.

**Comment by ChristianMurphy** [comment]
Thanks @apetro!
