### ISSUE TITLE
Readme link

### ISSUE THREAD

**Issue by jgribonvald** [Jasig/SurveyPortlet#16]
The link to documentation in the readme requires an account login
Could the documentation be brought into the repository for better public access?
Thanks!

**Comment by jgribonvald** [comment]
Thanks a lot Christian !

Also is it possible to get a link on screens examples ? It's to have an idea of possibilities.

Thanks

**Comment by ChristianMurphy** [comment]
Sure! Some additional screenshots and usage examples are incoming.
